ARG BASE_IMAGE=ibp-ncdu_mount_scan-base:latest

FROM $BASE_IMAGE

WORKDIR /ncdu_mount_scan

#COPY assets ./assets
#COPY bin ./bin
#COPY CHANGELOG.md ./CHANGELOG.md
#COPY conf ./conf
#COPY docs ./docs
#COPY lib ./lib
#COPY main.nf ./main.nf
#COPY nextflow.config ./nextflow.config
COPY README.md ./README.md

